### ISSUE TITLE
Compile errors

### ISSUE THREAD

**Issue by vogella** [LucasBullen/LSP4J_Tutorial#1]
@LucasBullen so you plan to keep this repo alive? I cloned it and tried to fixed a few compile errors (still the example is not yet working for me).

If you plan to keep this alive, I could send you a PR for my fix and open issues for the remaining issues. Would be a nice way for me to learn the LSPJ and LSPE story.

**Comment by LucasBullen** [comment]
Yes, i haven't kept this repo up to date, but agree that it would be a good resource to update. If you make any PRs I'll review and if you need anything just give me a ping

**Comment by vogella** [comment]
I found https://github.com/mickaelistria/eclipse-languageserver-demo/blob/master/README.md which is good enough for getting started.
